### PR TITLE
Updated the locateTopEven method

### PR DESCRIPTION
**Pull request by Jdiva1234**
fixed the spaces and changed indexOfTopEven to 1.

### CODE REVIEW

**Comment by Jdiva1234** [comment]
done

**Comment by SergeyOvchinnik** [comment]
This commit changes a lot of stuff all over the PoorCode.java file, please remove all changes outside of the locateTopEven method

**Comment by Jdiva1234** [comment]
please, check if it's good.

**Comment by SergeyOvchinnik** [comment]
Looks good, :shipit:

**Pull request merged**
